name: krishivikas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 11.2.2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  selectable_container: ^1.0.2
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_sign_in:
  pinput: ^1.2.2
  form_field_validator: ^1.1.0
  shared_preferences: ^2.0.12
  firebase_messaging: ^14.2.1
  image_picker: ^0.8.6+2
  # dependencies:
  #flutter_signin_button: ^2.0.0
  http: ^0.13.4
  flutter_facebook_auth: ^4.0.1
  permission_handler: ^10.0.0
  # permission_handler: ^8.3.0
  dio: ^4.0.4
  cached_network_image: ^3.2.0
  dropdown_search: ^2.0.1
  url_launcher: ^6.1.7
  # geolocator: ^8.2.0
  geolocator: ^9.0.1
  geocoding: ^2.0.2
  rename: ^2.0.1
  onesignal_flutter: ^3.3.1
  get: ^4.6.1
  video_player: ^2.4.0
  intl: ^0.17.0
  share_plus: ^4.1.0
  # flutter_share: ^2.0.0
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^9.5.3
  camera: ^0.10.3
  path_provider: ^2.0.11
  path: ^1.8.2
  device_info_plus: ^8.0.0
  file_picker: ^5.2.3
  in_app_update: ^4.0.1
  firebase_dynamic_links: ^5.0.11
  package_info_plus: ^3.0.2
  flutter_share: ^2.0.0
  photo_view: ^0.14.0
  filter_list: ^1.0.2
  store_redirect: ^2.0.1
  awesome_notifications: ^0.7.4+1
  font_awesome_flutter: ^10.4.0
  flutter_native_image: ^0.0.6+1
  easy_loading_button: ^0.3.2
  animated_custom_dropdown: ^1.5.0
  fluttertoast: ^8.2.2
  provider: ^6.0.5

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/kv_logo.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/others/
    - assets/icons/NewOld/
    - assets/icons/Category/
    - assets/icons/SubCategory/Fertilizers/
    - assets/icons/SubCategory/GoodsVehicle/
    - assets/icons/SubCategory/Harvester/
    - assets/icons/SubCategory/Implements/
    - assets/icons/SubCategory/Pesticides/
    - assets/icons/SubCategory/Seeds/
    - assets/icons/SubCategory/Tractor/
    - assets/icons/SubCategory/Tyres/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow-Black.ttf
          weight: 900
        - asset: assets/fonts/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Barlow-Thin.ttf
          weight: 100
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 600

    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
          weight: 400
