class TyresData {
  static String? type;
  static int? categoryId;
  static int? brandId;
  static int? modelId;
  static int? yearOfPurchase;
  static String? position;
  static String? description;
  static String? price;
  static int? IsNegotiable;
  static int? cityId;
  static int? stateId;
  static int? districtId;
  static int? countryId;
  static String? stateName;
  static String? cityName;
  static String? brandName;
  static String? lat;
  static String? long;
  static int? zipcode;
}
